- platform: command_line
  command: 'ping -c 1 Garage_1 | grep "1 received" | wc -l'
  name: 'Garage Control Online'
  sensor_class: connectivity
  payload_on: 1
  payload_off: 0
  
#- platform: mqtt
#  state_topic: kitchen/motion
#  name: Kitchen Motion
#  qos: 0
#  payload_on: MOTION
#  payload_off: NOMOTION
#  device_class: motion

- platform: command_line
  command: !secret den_cam_rcrding
  name: 'Den Camera Recording'
#  sensor_class: None
  payload_on: 1
  payload_off: 0

- platform: command_line
  command: !secret liv_rm_cam_rcrding
  name: 'Living Room Camera Recording'
#  sensor_class: None
  payload_on: 1
  payload_off: 0

- platform: command_line
  command: !secret garage_cam_rcrding
  name: 'Garage Camera Recording'
#  sensor_class: None
  payload_on: 1
  payload_off: 0

- platform: workday
  country: US
  province: OH

- platform: template
  sensors:
    vacation_monitor:
      friendly_name: 'Vacation Monitor'
      value_template: "{{ is_state('input_boolean.vacation', 'on') }}"

- platform: ping
  host: 192.168.1.67
  name: Desktop
  count: 2
  scan_interval: 20