#- platform: local_file
#  name: Main Pi Image
#  file_path: /home/redwngsrul/picture.jpg
  
# - platform: local_file
  # name: Remote Pi Image
  # file_path: /home/redwngsrul/pictures/picture.jpg

- platform: foscam
  name: Living Room Video
  ip: 192.168.1.96
  port: 88
  username: !secret cam_un
  password: !secret cam_pw

- platform: foscam
  name: Den Video
  ip: 192.168.1.97
  port: 88
  username: !secret cam_un
  password: !secret cam_pw

- platform: foscam
  name: Garage Video
  ip: 192.168.1.98
  port: 88
  username: !secret cam_un
  password: !secret cam_pw

#- #platform: mjpeg
  #mjpeg_url: http://192.168.1.94:8080/?action=stream
  #name: Den 2 Cam
  
#- platform: generic
 # name: Alex's Map Card
  #still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.pixelxl_pixelxl.attributes.latitude }},{{ states.device_tracker.pixelxl_pixelxl.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.pixelxl_pixelxl.attributes.latitude }},{{ states.device_tracker.pixelxl_pixelxl.attributes.longitude }}&key=AIzaSyB-Vkahvbd9Qpp5q8a81-xZSUIKuYheGBA%20limit_refetch_to_url_change:%20true
  #limit_refetch_to_url_change: true
  
# - platform: mjpeg
  # mjpeg_url: http://192.168.1.95:8080
  # name: Living Room 2 Cam
  
# - platform: local_file
  # name: Currently Playing
  # file_path: /home/redwngsrul/.homeassistant/www/ps4cam/currentgame.jpg

#- platform: generic
#  still_image_url: radar.weather.gov/ridge/Conus/centgrtlakes_loop.php
#  name: Weather
