#turn on fish tank lights at dusk
- alias: 'Fish Tank Lights'
  initial_state: true
  trigger:
    - platform: state
      entity_id: device_tracker.pixelxl_pixelxl
      to: 'home'
      for:
        minutes: 5
  action:
    - service: switch.turn_on
      entity_id: switch.fish_tank_white_light
#turn off tank lights at bedtime
- alias: 'No Lights at Bedtime'
  initial_state: true
  trigger:
    platform: time
    at: '22:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.fish_tank_white_light
#turn on tank lights in morning
- alias: 'Tank Lights on in Morning'
  initial_state: true
  trigger:
    - platform: time
      at: '05:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.fish_tank_blue_light