#turn on DEN light
- alias: 'Den Lamp ON'
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.den_motion
    from: '1'
    to: '2'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: switch.den_light
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.den_light

#turn off DEN light   
- alias: 'Den Lamp OFF'
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.den_motion
    to: '1'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: switch.den_light
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.den_light
